export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const START_LOCATION_FETCH = 'START_LOCATION_FETCH';
export const COMPLETE_LOCATION_FETCH = 'COMPLETE_LOCATION_FETCH';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const START_EVENT_LIST_FETCH = 'START_EVENT_LIST_FETCH';
export const COMPLETE_EVENT_LIST_FETCH = 'COMPLETE_EVENT_LIST_FETCH';
export const FETCH_EVENT_LIST = 'FETCH_EVENT_LIST';

